"""Public exception surface for EDEN.

Import errors from :mod:`eden.errors` rather than from submodules so that the
internal layout can change without breaking callers.
"""

from __future__ import annotations

from eden.errors.base import (
    ActionExecutionError,
    AgentCapabilityError,
    AgentError,
    AutomationError,
    ConfigurationError,
    CoreError,
    DependencyResolutionError,
    DeviceCommandError,
    DeviceNotFoundError,
    DeviceSafetyError,
    DeviceUnavailableError,
    EdenError,
    EmbeddingNotSupportedError,
    ExecutionError,
    GatewayError,
    HandlerNotFoundError,
    HardwareError,
    InterfaceError,
    InvalidConfigError,
    InvalidPlanError,
    InvalidRuleError,
    LifecycleError,
    MemoryCapacityError,
    MemoryNotFoundError,
    MemoryStorageError,
    MemorySubsystemError,
    MissingConfigError,
    ModelNotSupportedError,
    NoProviderAvailableError,
    NoSuitableAgentError,
    PermissionDeniedError,
    PlanningError,
    PluginLoadError,
    ProviderAuthenticationError,
    ProviderError,
    ProviderRateLimitError,
    ProviderResponseError,
    ProviderTimeoutError,
    ProviderUnavailableError,
    RegistryError,
    RollbackError,
    RuleNotFoundError,
    SecretResolutionError,
    TransportError,
    ValidationError,
    VerificationError,
)

__all__ = [
    "ActionExecutionError",
    "AgentCapabilityError",
    "AgentError",
    "AutomationError",
    "ConfigurationError",
    "CoreError",
    "DependencyResolutionError",
    "DeviceCommandError",
    "DeviceNotFoundError",
    "DeviceSafetyError",
    "DeviceUnavailableError",
    "EdenError",
    "EmbeddingNotSupportedError",
    "ExecutionError",
    "GatewayError",
    "HandlerNotFoundError",
    "HardwareError",
    "InterfaceError",
    "InvalidConfigError",
    "InvalidPlanError",
    "InvalidRuleError",
    "LifecycleError",
    "MemoryCapacityError",
    "MemoryNotFoundError",
    "MemoryStorageError",
    "MemorySubsystemError",
    "MissingConfigError",
    "ModelNotSupportedError",
    "NoProviderAvailableError",
    "NoSuitableAgentError",
    "PermissionDeniedError",
    "PlanningError",
    "PluginLoadError",
    "ProviderAuthenticationError",
    "ProviderError",
    "ProviderRateLimitError",
    "ProviderResponseError",
    "ProviderTimeoutError",
    "ProviderUnavailableError",
    "RegistryError",
    "RollbackError",
    "RuleNotFoundError",
    "SecretResolutionError",
    "TransportError",
    "ValidationError",
    "VerificationError",
]
