"""Configuration subsystem.

Nothing in EDEN reads the environment, a literal path, port, model name or
provider name directly. Every tunable enters through this package, is validated
once at startup, and is then handed to components as an immutable value object.
"""

from __future__ import annotations

from eden.config.enums import (
    ActionKind,
    AutomationStatus,
    Capability,
    CircuitState,
    DeviceKind,
    DeviceState,
    Environment,
    ExecutionStatus,
    FinishReason,
    HealthState,
    LogFormat,
    LogLevel,
    MemoryKind,
    PermissionMode,
    PrivacyTier,
    ProviderKind,
    RiskLevel,
    Role,
    RoutingStrategyName,
    TriggerKind,
)
from eden.config.loader import ConfigLoader, build_config, load_config
from eden.config.schema import (
    AutomationConfig,
    CircuitBreakerConfig,
    DeviceConfig,
    EdenConfig,
    ExecutionConfig,
    GatewayConfig,
    HardwareConfig,
    InterfaceConfig,
    LoggingConfig,
    MemoryConfig,
    ModelConfig,
    PathsConfig,
    ProviderConfig,
    RetryConfig,
    RouterConfig,
    RouterWeights,
    ServerConfig,
)
from eden.config.secrets import REDACTED, SecretResolver, SecretStr
from eden.config.sources import (
    ConfigSource,
    EnvironmentSource,
    MappingSource,
    TomlFileSource,
    deep_merge,
)

__all__ = [
    "REDACTED",
    "ActionKind",
    "AutomationConfig",
    "AutomationStatus",
    "Capability",
    "CircuitBreakerConfig",
    "CircuitState",
    "ConfigLoader",
    "ConfigSource",
    "DeviceConfig",
    "DeviceKind",
    "DeviceState",
    "EdenConfig",
    "Environment",
    "EnvironmentSource",
    "ExecutionConfig",
    "ExecutionStatus",
    "FinishReason",
    "GatewayConfig",
    "HardwareConfig",
    "HealthState",
    "InterfaceConfig",
    "LogFormat",
    "LogLevel",
    "LoggingConfig",
    "MappingSource",
    "MemoryConfig",
    "MemoryKind",
    "ModelConfig",
    "PathsConfig",
    "PermissionMode",
    "PrivacyTier",
    "ProviderConfig",
    "ProviderKind",
    "RetryConfig",
    "RiskLevel",
    "Role",
    "RouterConfig",
    "RouterWeights",
    "RoutingStrategyName",
    "SecretResolver",
    "SecretStr",
    "ServerConfig",
    "TomlFileSource",
    "TriggerKind",
    "build_config",
    "deep_merge",
    "load_config",
]
